version: '3.8'
services:
  app:
    container_name: express-tinkering
    build:
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: node --watch src/index.js
